pull_request_rules:
  - name: Automatic Dependabot merge
    conditions:
      - label=dependencies
      - head~=^dependabot
      - base=main
      - "check-success=ci/circleci: build"
    actions:
      merge:
        method: merge